source 'https://rubygems.org'

gem 'cucumber'
gem 'httparty'
gem 'rspec'
gem 'tshield'
gem 'json'
gem 'reportportal', git: 'https://github.com/reportportal/agent-ruby.git'

group :development do
  gem 'byebug'
  gem 'rubocop'
end
